-- CREATE TABLE products (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     price DECIMAL(10, 2) NOT NULL,
--     farmerId INT NOT NULL,
--     FOREIGN KEY (farmerId) REFERENCES farmers(id) ON DELETE CASCADE
-- );